### PR TITLE
Revert to using exec when running a shim

### LINKED ISSUE #475: Error message after exiting Elixir/Erlang using ctrl-\ when running with asdf v0.7.0
### Steps to reproduce

Upgraded asdf to 0.7.0 using `asdf update`, upgraded plugins using `asdf plugin-update --all`. Run an Elixir REPL: `iex`. Happens when exiting Erlang REPL `erl` as well.

### Expected behavior

Normally when exiting with `ctrl-c ctrl-c` or `ctrl-\` the app exits quietly.

### Actual behavior

When using `ctrl-c ctrl-c` app exits normally. When using `ctrl-\` I see the following output:

```bash
❯ iex
Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> /Users/craig/.asdf/lib/utils.sh: line 478: 13103 Quit: 3                 ( if [ "$version" = "system" ]; then
                      "$callback"; exit $?;
                                           fi; local plugin_path; plugin_path=$(get_plugin_path "$plugin_name"); local path; path="$(list_plugin_exec_paths "$plugin_name" "$full_version" | tr '\n' ':'):$PATH"; if [ ! -f "${plugin_path}/bin/exec-env" ]; then
                                                               PATH=$path "$callback"; exit $?;
                                                                                               fi; local install_path; install_path=$(find_install_path "$plugin_name" "$full_version"); ASDF_INSTALL_TYPE=$install_type; ASDF_INSTALL_VERSION=$version; ASDF_INSTALL_PATH=$install_path; export ASDF_INSTALL_TYPE; export ASDF_INSTALL_VERSION; export ASDF_INSTALL_PATH; source "${plugin_path}/bin/exec-env"; unset ASDF_INSTALL_TYPE; unset ASDF_INSTALL_VERSION; unset ASDF_INSTALL_PATH; PATH=$path "$callback"; exit $? )
                 /Users/craig/.asdf/lib/utils.sh: line 478: 12979 Quit: 3                 ( if [ "$version" = "system" ]; then
                               "$callback"; exit $?;
                                                    fi; local plugin_path; plugin_path=$(get_plugin_path "$plugin_name"); local path; path="$(list_plugin_exec_paths "$plugin_name" "$full_version" | tr '\n' ':'):$PATH"; if [ ! -f "${plugin_path}/bin/exec-env" ]; then
                                                                        PATH=$path "$callback"; exit $?;
     fi; local install_path; install_path=$(find_install_path "$plugin_name" "$full_version"); ASDF_INSTALL_TYPE=$install_type; ASDF_INSTALL_VERSION=$version; ASDF_INSTALL_PATH=$install_path; export ASDF_INSTALL_TYPE; export ASDF_INSTALL_VERSION; export ASDF_INSTALL_PATH; source "${plugin_path}/bin/exec-env"; unset ASDF_INSTALL_TYPE; unset ASDF_INSTALL_VERSION; unset ASDF_INSTALL_PATH; PATH=$path "$callback"; exit $? )
```

### Environment

MacOS 10.14.2 (18C54)

**asdf version**: 0.7.0

### PR DESCRIPTION
**Pull request by danhper**
As discussed, this reverts to the previous behavior of executing shims with `exec`.
This is a step back towards #409 but I do not think we have a way around it.
Fixes #475

### CODE REVIEW

File: lib/utils.sh [hunk 1]
```diff
@@ -489,49 +489,36 @@ with_plugin_env() {
     local version="${version_info[0]}"
   fi
 
-  # create a new subshell to keep env
-  (
```
Comment (Stratus3D) [inline lib/utils.sh]: Is this subshell not needed anymore?

**Comment by Stratus3D** [comment]
Also wasn't there an `eval` call that was going to be removed? I remember seeing `ev'al'` somewhere.

File: lib/utils.sh (hunk 1 above)
Comment (danhper) [reply lib/utils.sh]: I am not exactly sure why it was needed in the first place. Any idea? 
The issue with the subshell is that, as the callback was called from the shell, there would always be an extra `bash` process running which kind of defeats the point of `exec`.

**Comment by danhper** [comment]
The `ev'al'` call is still used by `reshim`, `install` and other hooks so I did not touch this.
For the subshell, I am not entirely sure so it would be great if somebody could confirm.
/cc @vic @HashNuke

File: lib/utils.sh (hunk 1 above)
Comment (Stratus3D) [reply lib/utils.sh]: I think it was used to contain the exported environment variables, but I'm not sure where they would leak if we didn't have it. So maybe it's not needed at all, but it was present prior to the change that remove `exec` I think.

Comment (danhper) [reply lib/utils.sh]: I understand that `exec-env` also exports env variables, which could "leak" but as asdf is executed in its own process, which will finally be replaced by the desired executable process, I do not really see why this would be an issue.
Maybe at some point in the past asdf was used as a function and not a command, so this was to avoid polluting shell environment?

Comment (danhper) [reply lib/utils.sh]: After a bit of digging I found that the subshell was introduced quite a while ago but there were not much details about why:
https://github.com/asdf-vm/asdf/commit/ab04ca9f559102f336dde513458816ed1fdb16bb#diff-969a0ff4a73b9d80109d01f5a51d7854
@HashNuke If you have a moment, it would be great if you could enlighten us :bulb:

Comment (Stratus3D) [reply lib/utils.sh]: Good find. No idea what the original intention was, but I don't see any reason why we'd still need this. Worst case scenario it would just be polluting some asdf code right?

Comment (danhper) [reply lib/utils.sh]: > Worst case scenario it would just be polluting some asdf code right?

Yes, I think that this is all that could happen.

**Comment by danhper** [comment]
@Stratus3D Although I am not 100% about this, I think that it should be better than the current state so I will merge and release 0.7.1

**Comment by Stratus3D** [comment]
Thanks @danhper ! I think that was a good decision. 0.7.1 has definitely fixed some big issues, and I haven't come across any new problems.
